# Path related
dataset_path: data/cs-training.csv
dataset_validation: data/cs-test.csv
train_set_path:
  - data/X_train.csv
  - data/y_train.csv
test_set_path:
  - data/X_test.csv
  - data/y_test.csv

# data-types related
float_columns:
 - DebtRatio

 #INITIAL SETTINGS
data_source:
  directory:
  filename:
  column_names:
  drop_columns:
  target_name:
  test_size:
  random_state:


#kNN parameters
model:
  n_neighbors:
  weights:
  algorithm:
  leaf_size:
  p:
  metric:
  n_jobs:
  model_directory:
  model_name:
